import type { SupportedLanguage } from "@/domain/shared/types";

// Customer-facing PDF labels per supported document language. These are pure
// presentation strings; no business logic depends on them.
export interface QuotePdfStrings {
  documentTitle: string;
  documentNumber: string;
  versionLabel: string; // e.g. "Version"
  issueDate: string;
  validUntil: string;
  introTitle: string;
  status: string;
  statusLabels: Record<"draft" | "sent" | "accepted" | "rejected", string>;
  customer: string;
  project: string;
  colNr: string;
  colWork: string;
  colDescription: string;
  colQuantity: string;
  colUnit: string;
  colUnitPrice: string;
  colDiscount: string;
  colTotal: string;
  subtotal: string;
  discount: string;
  taxBase: string;
  vat: string;
  total: string;
  commercialTerms: string;
  validity: string;
  paymentTerms: string;
  executionDuration: string;
  inclusions: string;
  exclusions: string;
  companyTerms: string;
  notes: string;
  page: string; // "Page {n} / {total}" template using {n} and {total}
}

// Short, language-neutral unit symbols for the document table.
export const UNIT_SYMBOLS: Record<string, string> = {
  m2: "m²",
  m: "m",
  m3: "m³",
  pcs: "buc",
  hour: "h",
  day: "zi",
  kg: "kg",
  l: "l",
  set: "set",
  service: "serv",
};

export const PDF_STRINGS: Record<SupportedLanguage, QuotePdfStrings> = {
  ro: {
    documentTitle: "Deviz",
    documentNumber: "Număr document",
    versionLabel: "Versiunea",
    issueDate: "Data emiterii",
    validUntil: "Valabil până la",
    introTitle: "Introducere",
    status: "Status",
    statusLabels: {
      draft: "Schiță",
      sent: "Trimis",
      accepted: "Acceptat",
      rejected: "Respins",
    },
    customer: "Client",
    project: "Proiect",
    colNr: "Nr.",
    colWork: "Lucrare",
    colDescription: "Descriere",
    colQuantity: "Cantitate",
    colUnit: "UM",
    colUnitPrice: "Preț unitar",
    colDiscount: "Discount",
    colTotal: "Total",
    subtotal: "Subtotal",
    discount: "Reducere",
    taxBase: "Bază TVA",
    vat: "TVA",
    total: "Total",
    commercialTerms: "Condiții comerciale",
    validity: "Valabilitate",
    paymentTerms: "Condiții de plată",
    executionDuration: "Durată estimată execuție",
    inclusions: "Include",
    exclusions: "Exclude",
    companyTerms: "Termeni companie",
    notes: "Note",
    page: "Pagina {n} / {total}",
  },
  ru: {
    documentTitle: "Смета",
    documentNumber: "Номер документа",
    versionLabel: "Версия",
    issueDate: "Дата выпуска",
    validUntil: "Действительно до",
    introTitle: "Введение",
    status: "Статус",
    statusLabels: {
      draft: "Черновик",
      sent: "Отправлено",
      accepted: "Принято",
      rejected: "Отклонено",
    },
    customer: "Клиент",
    project: "Проект",
    colNr: "№",
    colWork: "Работа",
    colDescription: "Описание",
    colQuantity: "Кол-во",
    colUnit: "Ед.",
    colUnitPrice: "Цена за ед.",
    colDiscount: "Скидка",
    colTotal: "Итого",
    subtotal: "Промежуточный итог",
    discount: "Скидка",
    taxBase: "База НДС",
    vat: "НДС",
    total: "Итого",
    commercialTerms: "Коммерческие условия",
    validity: "Срок действия",
    paymentTerms: "Условия оплаты",
    executionDuration: "Ориентировочный срок выполнения",
    inclusions: "Включено",
    exclusions: "Не включено",
    companyTerms: "Условия компании",
    notes: "Примечания",
    page: "Страница {n} / {total}",
  },
  en: {
    documentTitle: "Estimate",
    documentNumber: "Document number",
    versionLabel: "Version",
    issueDate: "Issue date",
    validUntil: "Valid until",
    introTitle: "Introduction",
    status: "Status",
    statusLabels: {
      draft: "Draft",
      sent: "Sent",
      accepted: "Accepted",
      rejected: "Rejected",
    },
    customer: "Customer",
    project: "Project",
    colNr: "No.",
    colWork: "Work",
    colDescription: "Description",
    colQuantity: "Quantity",
    colUnit: "Unit",
    colUnitPrice: "Unit price",
    colDiscount: "Discount",
    colTotal: "Total",
    subtotal: "Subtotal",
    discount: "Discount",
    taxBase: "VAT base",
    vat: "VAT",
    total: "Total",
    commercialTerms: "Commercial terms",
    validity: "Validity",
    paymentTerms: "Payment terms",
    executionDuration: "Estimated execution duration",
    inclusions: "Inclusions",
    exclusions: "Exclusions",
    companyTerms: "Company terms",
    notes: "Notes",
    page: "Page {n} / {total}",
  },
  it: {
    documentTitle: "Preventivo",
    documentNumber: "Numero documento",
    versionLabel: "Versione",
    issueDate: "Data di emissione",
    validUntil: "Valido fino al",
    introTitle: "Introduzione",
    status: "Stato",
    statusLabels: {
      draft: "Bozza",
      sent: "Inviato",
      accepted: "Accettato",
      rejected: "Rifiutato",
    },
    customer: "Cliente",
    project: "Progetto",
    colNr: "N.",
    colWork: "Lavoro",
    colDescription: "Descrizione",
    colQuantity: "Quantità",
    colUnit: "UM",
    colUnitPrice: "Prezzo unitario",
    colDiscount: "Sconto",
    colTotal: "Totale",
    subtotal: "Subtotale",
    discount: "Sconto",
    taxBase: "Base IVA",
    vat: "IVA",
    total: "Totale",
    commercialTerms: "Condizioni commerciali",
    validity: "Validità",
    paymentTerms: "Condizioni di pagamento",
    executionDuration: "Durata stimata esecuzione",
    inclusions: "Incluso",
    exclusions: "Escluso",
    companyTerms: "Termini azienda",
    notes: "Note",
    page: "Pagina {n} / {total}",
  },
  fr: {
    documentTitle: "Devis",
    documentNumber: "Numéro du document",
    versionLabel: "Version",
    issueDate: "Date d'émission",
    validUntil: "Valable jusqu'au",
    introTitle: "Introduction",
    status: "Statut",
    statusLabels: {
      draft: "Brouillon",
      sent: "Envoyé",
      accepted: "Accepté",
      rejected: "Refusé",
    },
    customer: "Client",
    project: "Projet",
    colNr: "N°",
    colWork: "Travaux",
    colDescription: "Description",
    colQuantity: "Quantité",
    colUnit: "Unité",
    colUnitPrice: "Prix unitaire",
    colDiscount: "Remise",
    colTotal: "Total",
    subtotal: "Sous-total",
    discount: "Remise",
    taxBase: "Base TVA",
    vat: "TVA",
    total: "Total",
    commercialTerms: "Conditions commerciales",
    validity: "Validité",
    paymentTerms: "Conditions de paiement",
    executionDuration: "Durée d'exécution estimée",
    inclusions: "Inclus",
    exclusions: "Exclus",
    companyTerms: "Conditions de l'entreprise",
    notes: "Notes",
    page: "Page {n} / {total}",
  },
  de: {
    documentTitle: "Kostenvoranschlag",
    documentNumber: "Dokumentnummer",
    versionLabel: "Version",
    issueDate: "Ausstellungsdatum",
    validUntil: "Gültig bis",
    introTitle: "Einleitung",
    status: "Status",
    statusLabels: {
      draft: "Entwurf",
      sent: "Gesendet",
      accepted: "Angenommen",
      rejected: "Abgelehnt",
    },
    customer: "Kunde",
    project: "Projekt",
    colNr: "Nr.",
    colWork: "Arbeit",
    colDescription: "Beschreibung",
    colQuantity: "Menge",
    colUnit: "Einheit",
    colUnitPrice: "Einzelpreis",
    colDiscount: "Rabatt",
    colTotal: "Gesamt",
    subtotal: "Zwischensumme",
    discount: "Rabatt",
    taxBase: "MwSt.-Basis",
    vat: "MwSt.",
    total: "Gesamt",
    commercialTerms: "Kommerzielle Bedingungen",
    validity: "Gültigkeit",
    paymentTerms: "Zahlungsbedingungen",
    executionDuration: "Geschätzte Ausführungsdauer",
    inclusions: "Enthalten",
    exclusions: "Ausgeschlossen",
    companyTerms: "Unternehmensbedingungen",
    notes: "Anmerkungen",
    page: "Seite {n} / {total}",
  },
  es: {
    documentTitle: "Presupuesto",
    documentNumber: "Número de documento",
    versionLabel: "Versión",
    issueDate: "Fecha de emisión",
    validUntil: "Válido hasta",
    introTitle: "Introducción",
    status: "Estado",
    statusLabels: {
      draft: "Borrador",
      sent: "Enviado",
      accepted: "Aceptado",
      rejected: "Rechazado",
    },
    customer: "Cliente",
    project: "Proyecto",
    colNr: "N.º",
    colWork: "Trabajo",
    colDescription: "Descripción",
    colQuantity: "Cantidad",
    colUnit: "Unidad",
    colUnitPrice: "Precio unitario",
    colDiscount: "Descuento",
    colTotal: "Total",
    subtotal: "Subtotal",
    discount: "Descuento",
    taxBase: "Base IVA",
    vat: "IVA",
    total: "Total",
    commercialTerms: "Condiciones comerciales",
    validity: "Validez",
    paymentTerms: "Condiciones de pago",
    executionDuration: "Duración estimada de ejecución",
    inclusions: "Incluye",
    exclusions: "Excluye",
    companyTerms: "Términos de la empresa",
    notes: "Notas",
    page: "Página {n} / {total}",
  },
};

// Locale used only for number/date grouping in the document, per language.
export const PDF_LOCALES: Record<SupportedLanguage, string> = {
  ro: "ro-RO",
  ru: "ru-RU",
  en: "en-US",
  it: "it-IT",
  fr: "fr-FR",
  de: "de-DE",
  es: "es-ES",
};
